#!/bin/bash

# 1. Remove ansible-st2
# 2. Copy upstream ansible-st2
# 3. Go into upstream ansible-st2 dir and run: ansible-galaxy install -r roles/mistral/requirements.yml
# 4. Symlink arteria specific stuff with this script
# 5. Commit changes

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd $SCRIPT_PATH/../ansible-st2/
ln -fs ../ansible-st2-local/inventories inventories
ls -l | grep ^l

cd $SCRIPT_PATH/../ansible-st2/playbooks
ln -fs ../../ansible-st2-local/playbooks/* .
ls -l | grep ^l

cd $SCRIPT_PATH/../ansible-st2/roles
ln -fs ../../ansible-st2-local/roles/* .
ls -l | grep ^l

