---

- include: arteria_mailclient.yml
  tags: arteria_mailclient

- include: conf.yml
  tags: arteria_master_conf

- name: Pause for 1 minute until stackstorm services are up and online
  pause: minutes=1

# FIXME: These steps has to be done manually for non-test systems at the moment, 
# because we do not want passwords on live systems in clear text. Have to find
# a better method later. 
- include: register_components.yml
  tags: arteria_register_components
  when: arteria_environment == "staging" 

- name: Override paramiko setting (currently buggy)
  sudo: yes
  ini_file:
    dest=/etc/st2/st2.conf
    section=ssh_runner
    option=use_paramiko_ssh_runner
    value=False
    backup=yes
  notify: 
    - restart st2
  tags: arteria_paramiko_override

- name: Ensure api is reachable from web-ui
  sudo: yes
  ini_file:
    dest=/etc/st2/st2.conf
    section=api
    option=allow_origin
    value=http://{{ ansible_hostname }}:8080
    backup=yes
  notify:
    - restart st2
  tags: arteria_master_conf
